#!/bin/zsh

export PUB_HOSTED_URL="https://pub.flutter-io.cn"
export FLUTTER_STORAGE_BASE_URL="https://storage.flutter-io.cn"
export JAVA_HOME="$HOME/development/jdk17/Contents/Home"
export ANDROID_HOME="$HOME/Library/Android/sdk"

exec "$HOME/development/flutter/bin/flutter" "$@"
